### ISSUE TITLE
AutoCompleteLevenshtein bug

### ISSUE THREAD

**Issue by kasyanovandrii** [DanHarltey/Fastenshtein#4]
Please try test
[Fact]
public void Shorter_Value_Is_Distance_Test2()
{
     Test("tst", "test", 1);
}

for AutoCompleteLevenshteinTests

it fails and  AutoCompleteLevenshtein.Distance returns 2 instead of 1

**Comment by DanHarltey** [comment]
Hi,
Apologies for the delay in getting back to you.

The AutoCompleteLevenshtein is a bit of a funny one. I was asked to do this version by someone I knew.
It is designed for an autocomplete/typeahead fields. If the user types "Bendorm" it should closely match "Benidorm, Spain".

It does this only matching to the length for the first parameter. This is to avoid Distance("Bendorm", "Benidorm, Spain") equalling 8. Instead they are given 2 distance representing a closer match.

In this example as the first argument has a length of three the second argument is shorted from "test" to “tes”. "tst" is 2 distance away from "tes" so in this case AutoCompleteLevenshtein is working as expected.
