### ISSUE TITLE
Parallel Levenshtein

### ISSUE THREAD

**Issue by jppeterson** [DanHarltey/Fastenshtein#7]
It seems you should not reuse an instance of `Levenshtein` across multiple threads. If it's not worth fixing, perhaps a note in the README specifiying not to multithread calls to `DistanceFrom` on a shared instance. The static method works fantastic. For my examples below I'm calculating the distance of a user inputted drug name against a cache of ~32k drugs.

For example this produces incorrect results:
```
var returnItems = new ConcurrentBag<(int distance, Drug drug)>();
string item = "Ibuprophen";//user input
Levenshtein lev = new Levenshtein(item);
Parallel.ForEach(await GetFullCache(), drug =>//~32k Drug classes with Name property
{
    int distance = lev.DistanceFrom(drug.Name);
    if (distance <= 10)
    {
        returnItems.Add((distance, drug));
    }
});
```
Whereas this produces expected results:
```
var returnItems = new ConcurrentBag<(int distance, Drug drug)>();
string item = "Ibuprophen";
Parallel.ForEach(await GetFullCache(), drug =>
{
    int distance = Levenshtein.Distance(item, drug.Name);
    if (distance <= 10)
    {
        returnItems.Add((distance, drug));
    }
});
```

**Comment by jppeterson** [comment]
Dug into the source of `Levenshtein` and found `private readonly int[] costs;` which is reused for each call to `DistanceFrom`. Explains the "quicker due to less memory allocation" comment in README. I'll close this issue - note to readers not to use the instance method across multiple threads.

**Comment by DanHarltey** [comment]
I have added a little text to warn others. Thank you for getting in touch and your feedback. Always happy to hear people are using Fastenshtein.

Cheers
Dan
