### ISSUE TITLE
Substitution

### ISSUE THREAD

**Issue by andrejbratukhin** [DanHarltey/Fastenshtein#8]
Hi!
substitution operation is missing.

**Comment by DanHarltey** [comment]
Hi,

I do not believe it is. Please could you provide an example where you have found it is not working as you expect? 

There are unit tests within the solution. There is a test called: Substitution_Adds_One_Distance_Test
This test is substitution and it is passing.

Thanks,
Dan

**Comment by DanHarltey** [comment]
Closing. Can be reopened if any examples are provided.
